# -*- coding: utf-8 -*-
"""Resume_AI_Assignment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Y_1y2d-e2pby5oe29e5dXIFW7u-BHQtt

# 🧠 Resume Screening AI Assistant
This Colab notebook will guide you through:
- Generating a synthetic resume dataset
- Training a classification model
- Launching a Streamlit app with ngrok
"""

# 1. Upload the assignment zip (assignment_ready.zip) from your local machine
from google.colab import files
uploaded = files.upload()

# Commented out IPython magic to ensure Python compatibility.
!unzip -o assignment_ready_v2.zip -d /content/
# %cd /content/resume_assignment_v2

# 3. Generate synthetic dataset (100 resumes across 10 categories)
!python generate_dataset.py
!head synthetic_resume_dataset.csv

# 4. Train the model
!python train.py --data synthetic_resume_dataset.csv --model_dir models

# 5. Launch the Streamlit app with ngrok tunnel
import os
os.environ["NGROK_AUTH_TOKEN"] = "33F9rYSlmnYOfnEilj7O5EnT8lv_7m7o19LmXuRDwsmHtnHm1"
!python launch_colab.py

